### ISSUE TITLE
it.each and describe.each

### ISSUE THREAD

**Issue by roughsoft** [microsoft/playwright-runner#40] opened 2020-04-29 06:28 UTC
describe.each if you keep duplicating the same test suites with different data. describe.each allows you to write the test suite once and pass data in.
https://jestjs.io/docs/en/api#describeeachtablename-fn-timeout

**Comment by JoelEinbinder** [comment] 2020-05-01 08:02
duplicate of #34

**Closed by JoelEinbinder** 2020-05-01 08:02 UTC
